version: '3.7'

services:
  url_shortener_django:
    env_file:
      - .env
    build:
      context: .
    ports:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - url_shortener_django
